# Generated by Django 4.2.7 on 2025-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
