# Generated by Django 4.2.7 on 2025-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_application_resume_application_resume_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry', 'Entry Level'), ('Mid', 'Mid Level'), ('Senior', 'Senior Level'), ('Lead', 'Lead'), ('Executive', 'Executive')], default='Mid', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Remote', 'Remote')], default='Full-time', max_length=20),
        ),
    ]
