# Generated by Django 4.2.7 on 2025-08-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_job_experience_level_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
